### ISSUE TITLE
Error with pushyMeInstall

### ISSUE THREAD

**Issue by pierresh** [LokeshPatel/Cordova-Plugin-CDVPushyMe#1]
Hello,

Thanks a lot for your plugin! Nevertheless the error callback is always called by the function navigator.CDVPushyMe.pushyMeInstall (point 1) in readme) and I get the following error message: _Invalid action_.

Also, for your information, the function pushyMeID works well, I get the ID of my phone, but the application crashes when I send a simple test push through the page [https://pushy.me/docs/test](https://pushy.me/docs/test). I modified the package name in files _CDVPlushyMePlugin.java_ and _PushReceiver.java_ but I get the same result.

Do you have any idea where the problem may come from?

Thanks!

**Comment by LokeshPatel** [comment]
Hi, 
Thanks for your support.
1) Error message: Invalid action. : fixed and committed, Please update CDVPlushyMePlugin.java with latest.
2) App Crash: Please send me more details like: device name, android version and crash error log.

**Comment by pierresh** [comment]
Hello,

Thanks a lot for your prompt feedback. But it seems that CDVPlushyMePlugin.java is not updated yet in the master branch (its last commit is shown 2 days ago).

Thanks!

**Comment by LokeshPatel** [comment]
Hi,
Find update: https://github.com/LokeshPatel/Cordova-Plugin-CDVPushyMe/blob/master/src/android/CDVPlushyMePlugin.java

**Comment by pierresh** [comment]
Thanks a lot for your quick update. I do not get anymore the error with the function _pushyMeInstall_ but the success callback is not called either..

My app still crashes when I send a test push. Here is below the log I get with CatLog when the app crash, bot sure it is really useful..:
![1 pic_hd](https://cloud.githubusercontent.com/assets/7520095/12948781/340c93d0-d03f-11e5-876d-91d1b6e301a1.jpg)

My phone is a XiaoMi 2S running Android 5.0.2 / MIUI 7.1.

**Comment by LokeshPatel** [comment]
Hi,
I have updated the code for "XiaoMi" mobile crash issue. Check out the latest code and try.
I hope!!, Working fine in your end.
Thanks,

**Comment by pierresh** [comment]
Hello, thanks a lot for your update. Nevertheless I get the same results..

I noticed that the success callback of the function _navigator.CDVPushyMe.pushyMeInstall_ is called only when I clear the data and cache of my app in Settings/Application. Then, when I reload my app, the success callback won't be called (error callback as well) till I clear again data and cache.

Thanks!

**Comment by LokeshPatel** [comment]
Hi, I try to reproduce but not getting success. please modify below code 

Try : PushReceiver.java file line no. 58

```
 Notification.Builder mBuilder =
                new Notification.Builder(context)
            .setDefaults(defaults)
            .setSmallIcon(context.getApplicationInfo().icon)
            .setWhen(System.currentTimeMillis())
            .setContentTitle(appName)
            .setTicker(extras.getString("title"))
            .setContentIntent(contentIntent)
            .setAutoCancel(true);
```

Update with : 

```
  Notification.Builder mBuilder =
        new Notification.Builder(context)
            .setDefaults(defaults)
            .setWhen(System.currentTimeMillis())
            .setContentTitle(appName)
            .setTicker(extras.getString("title"))
            .setContentIntent(contentIntent)
            .setAutoCancel(true);
```

**Comment by pierresh** [comment]
Perfect! It does not crash any more :smile: Thanks a lot for your work!

**Comment by Andrewtop** [comment]
Hello!
Getting same issue but all that you described doesn't help me.
Android 4.1.2 + emulator 5.1.1 .
Sucess or Error callback never called
