### ISSUE TITLE
Only the latest notification is shown in the status bar

### ISSUE THREAD

**Issue by pierresh** [LokeshPatel/Cordova-Plugin-CDVPushyMe#2]
Hello,

Thanks again for the plugin, I made additional tests on 2 Android phones and it works quite well. I just found one issue when several notifications are undead. Only the latest notification is shown in the status bar and the badge on app's icon still show 1 instead of the number of unread notifications.

Thanks and best regards!

**Comment by LokeshPatel** [comment]
Hi,
Update plugin with some changes. Also update badge number.
I hope!!! you like :)
Thanks,
Lokesh Patel
